### ISSUE TITLE
Music clue error when using from Youtube

### ISSUE THREAD

**Issue by KarlTheCobra** [krawthekrow/pi-connect-maker#5]
When I attempt to use music clues from youtube I get the error: Input stream error: Status code: 403.

**Comment by krawthekrow** [comment]
Youtube changes its interface frequently, so that feature isn't going to be working more likely than not (and isn't guaranteed to be supported indefinitely). Usually you can get it working by updating the ytdl-core dependency, but if that doesn't work or you aren't technically inclined, you can download the audio yourself and use the `audio/` mechanism to get them in.

I'll leave this open for me to document the above in the README, but due to the frequency of Youtube interface changes, I wouldn't be checking in a fix for this generally unless I personally use the feature or someone submits a PR.

**Comment by KarlTheCobra** [comment]
Thanks for the quick answer and for makimg the program I will look into it.

man. d. 14. okt. 2024 23.13 skrev Mark Theng ***@***.***>:

**Comment by krawthekrow** [comment]
I've updated the documentation, thanks for the change and your patience!
